version: '3.4'

services:
  minave.app:
    image: ${DOCKER_REGISTRY-}minaveapp
    build:
      context: Minave.APP
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/app/node_modules'
    ports:
       - "2000:3000"
    restart: always
  minave.api:
    image: ${DOCKER_REGISTRY-}minaveapi
    build:
      context: .
      dockerfile: Minave.API/Dockerfile
    ports:
       - "1500:5000"
    restart: always